### ISSUE TITLE
Plugin not available for QGIS 3.0+?

### ISSUE THREAD

**Issue by kylesomerville** [crocovert/networks#1]
As title - this plugin does not appear within repositories for QGIS 3.0+.

**Comment by crocovert** [comment]
Hello,


Yes sorry, the plugin isn't available for Qgis yet.
I need to upgrade it. I'm working on it currently, and I will provide a  
Qgis 3 compatible version soon which will be available as a set of 
processing algorithms

Thank you for your interest


Patrick PALMIER
Responsable du groupe Mobilités et Territoires
tél:+33 (0)3 20 49 60 70
mob:+33 (0)7 77 34 25 07
<cerema_html_7f500ad39ffdff4e.png>

Centre d’études et d’expertise sur les risques, l’environnement, la 
mobilité et l’aménagement - *www.cerema.fr*
Direction territoriale Nord-Picardie – 44 terrue Jean Bart -CS 20275 - 
59019 Lille Cedex
Siège social : Cité des Mobilités - 25 avenue François Mitterrand - CS 
92 803 - 69674 Bron Cedex - tél : +33 (0)4 72 14 30 30

**Comment by el-skrat** [comment]
bonjour,

Egalement très interessé par le portage de votre plugin sur QGIS 3.0. Merci pour le travail !

**Comment by crocovert** [comment]
Hello,

A first version of the plugin for Qgis 3.+ has been uploaded .
It works as an algorithm provider allowing run in batch mode and use in 
processing models
