### ISSUE TITLE
inport_gtfs.py fails on reading Stop Times

### ISSUE THREAD

**Issue by cliffordsnow** [crocovert/networks#11]
When I attempt to import [Skagit Transit GTFS](https://mycloud.snowandsnow.us/index.php/s/mWHM7iyzqFsqYTp) I get the following error on both Linux and MacOS:

QGIS version: 3.8.2-Zanzibar
Qt version: 5.12.4
GDAL version: 2.3.2
GEOS version: 3.7.1-CAPI-1.11.1 27a5e771
PROJ version: Rel. 5.2.0, September 15th, 2018
Processing algorithm…
Algorithm 'GTFS import' starting…
Input parameters:
{ 'DEBUT_PERIODE' : '10/09/2019', 'ENCODAGE' : 'utf_8_sig', 'FIN_PERIODE' : '10/09/2019', 'PREFIXE' : 'st', 'PROJ' : QgsCoordinateReferenceSystem('EPSG:4326'), 'REP_GTFS' : '/home/clifford/NextCloud/OSM/Skagit_GTFS', 'REP_SORTIE' : 'TEMPORARY_OUTPUT', 'T1' : '00:00:00', 'T2' : '23:59:59' }

Lecture des stops
reading calendar dates...
Reading routes...
Reading trips...
Reading stop times...
Traceback (most recent call last):
File "/home/clifford/.local/share/QGIS/QGIS3/profiles/default/python/plugins/networks/import_gtfs.py", line 391, in processAlgorithm
hi1=QTime(int(elements[ihdep][0:2]),int(elements[ihdep][3:5]),int(elements[ihdep][6:8]))
ValueError: invalid literal for int() with base 10: ''

Execution failed after 0.04 seconds

**Comment by crocovert** [comment]
Hello,

Use first the script "Prepare GTFS" which will clean the files. Il will 
generates a new GTFS dataset.
Then use "Import GTFS" using the new data set and it should work.
It works for me.
