### ISSUE TITLE
Update Field using formula not working

### ISSUE THREAD

**Issue by hugonbgg** [crocovert/networks#14]
I am using this formula _replace(replace(replace(layer_property(@layer_id, 'path'),'C:/Users/Hugo/Google Drive/Consultorias/De olho nos 2021/Entrega/testes/',''),@layer_name,''),'/.gpkg','')_ and it is not working, the field remains null. The same formula works on the field calculator.

I'm using Windows 10 and I think it's something about the path, how it is interpreted, but I couldn't solve it. I put the files on C: and the problem remained the same. Even if I use the formula _layer_property (@layer_id, 'path')_ it doesn't work.

![image](https://user-images.githubusercontent.com/11204577/105616854-8617bb80-5db8-11eb-9a0b-acfe4c632033.png)
![image](https://user-images.githubusercontent.com/11204577/105616862-8ca63300-5db8-11eb-80fa-a9ce5f5cb39c.png)

Thanks

**Comment by crocovert** [comment]
hello,

I fixed the problem. I've uploaded a new version of the plugin.
It will be available as soon as it will be approved by qgis team


https://plugins.qgis.org/plugins/networks/


Best regards

---



Le 24/01/2021 00:21, > notifications a écrit :
