### ISSUE TITLE
Bug "Matrice à partir d'une table"

### ISSUE THREAD

**Issue by AureClai** [crocovert/networks#17]
![image](https://github.com/crocovert/networks/assets/15649177/0381d2c4-f4b0-4ff2-8176-d212d462637c)

Le paramètre Demande devrait être une expression et pas un chiffre.

**Comment by AureClai** [comment]
![image](https://github.com/crocovert/networks/assets/15649177/31d5c04a-27e3-40d6-bce1-34d57f47f968)

A changer par : 
```python
self.addParameter(
    QgsProcessingParameterExpression(
                self.NB_PASSAGERS,
                self.tr('Demand'),
                parentLayerParameterName=self.POLES,
                optional=False,
                defaultValue='demand'
      )
)
```

et 

```python
nb_passagers=self.parameterAsDouble(parameters,self.NB_PASSAGERS,context)
```

par 
```python
nb_passagers=self.parameterAsExpression(parameters,self.NB_PASSAGERS,context).strip("'").strip("\"")
```

**Comment by crocovert** [comment]
Thank you AureClai for having implemented this feature.
I can close the issue
