### ISSUE TITLE
Bug with new release Networks plugin

### ISSUE THREAD

**Issue by BeppeSpina88** [crocovert/networks#20]
Good evening, since the last plugin update it no longer works on Qgis. Even old releases don't work.

![Networks](https://github.com/user-attachments/assets/12d9fd92-fd92-4d5c-bdac-fafed6f479b1)

**Comment by crocovert** [comment]
Hi,

I just pushed a new version
I hope it will fix it

**Comment by BeppeSpina88** [comment]
How long until I can download it on Qgis? thk

**Comment by crocovert** [comment]
Hello,

You have to wait that a moderator validates the version.
But you can also already download the version on plugins.qgis.org and install it manually with 'install from zip file'

**Comment by crocovert** [comment]
The version has been validated. 
Without further information if it works now or not, I close this issue
