### ISSUE TITLE
Can you reverse the 'Build graph' function with 'i' 'j' output to the v1.2.9 with the number series

### ISSUE THREAD

**Issue by huxiaoxi1992** [crocovert/networks#3]
I update my QGIS  and the networks plugins to 3.x, but the output of the build grapha function shows that the attributes in i and j are different from the 2.x version.
The 2.x version returns the number series and the 3.x returns a geometry coordinates string.

In fact, this function is also can be used in [pgrouting](https://docs.pgrouting.org/latest/en/pgr_createTopology.html#pgr-create-topology)(a network plugin in pgsql) called pgr_createTopology, which is the base of the network analysis in pgsql.

But all of my geometry data is producted in QGIS, I don't want to import the data into the database before all data completed. I find this plugin in QGIS and use this function.

Is this feature related to other new features? If not, I hope you can reverse this function or add some options.

**Comment by crocovert** [comment]
Hello,
It's done
You can choose now either  "number series" or "geographic string"

Patrick PALMIER
Responsable du groupe Mobilités et Territoires
tél:+33 (0)3 20 49 60 70
mob:+33 (0)7 77 34 25 07
<cerema_html_7f500ad39ffdff4e.png>

Centre d’études et d’expertise sur les risques, l’environnement, la 
mobilité et l’aménagement - *www.cerema.fr*
Direction territoriale Nord-Picardie – 44 terrue Jean Bart -CS 20275 - 
59019 Lille Cedex
Siège social : Cité des Mobilités - 25 avenue François Mitterrand - CS 
92 803 - 69674 Bron Cedex - tél : +33 (0)4 72 14 30 30
