### ISSUE TITLE
Prepare GTFS fails with Google's demo GTFS

### ISSUE THREAD

**Issue by anitagraser** [crocovert/networks#4]
I downloaded the offical Google GTFS sample dataset (https://developers.google.com/transit/gtfs/examples/gtfs-feed) and tried to run Prepare GTFS but it fails with:

```
Processing algorithm…
Algorithm 'Prepare GTFS' starting…
Input parameters:
{ 'PREFIXE_RESEAU' : 'ABC', 'REP_RESULTAT' : 'C:/Users/anita/AppData/Local/Temp/processing_ac56f85d2059492b837da52355f1519b/70fee6b44d1148438f214a744e90dc7d/REP_RESULTAT', 'REP_SOURCE' : 'E:/Geodata/GTFS/sample-feed', 'SPLIT_FORMULA' : '[-8:]', 'UIC' : False }

Traceback (most recent call last):
File "C:/Users/anita/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\networks\prepare_gtfs.py", line 143, in processAlgorithm
self.importGTFS(rep_source,rep_resultat,prefixe_reseau,uic,split_formula)
File "C:/Users/anita/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\networks\prepare_gtfs.py", line 303, in importGTFS
shapes2=codecs.open(sortie+'/shapes.txt','w',encoding='utf_8_sig')
File "C:\OSGEO4~1\apps\Python36\lib\codecs.py", line 895, in open
file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/anita/AppData/Local/Temp/processing_ac56f85d2059492b837da52355f1519b/70fee6b44d1148438f214a744e90dc7d/REP_RESULTAT/shapes.txt'

Execution failed after 0.13 seconds

Loading resulting layers
Algorithm 'Prepare GTFS' finished
```

**Comment by crocovert** [comment]
Hello,
Thank you for your feedback.
The bug is now fixed. The GTFS sample dataset is now working.

**Comment by anitagraser** [comment]
Thank you! Do you have some documentation that explains the general workflow and order for using all the different tools in the toolbox?

**Comment by crocovert** [comment]
Yes I found it trying to fix your previous bug, I published a new 
version on the plugin repository, but it has not been approved yet
With the new version, this bug will be fixed too

Patrick PALMIER
Responsable du groupe Mobilités et Territoires
tél:+33 (0)3 20 49 60 70
mob:+33 (0)7 77 34 25 07
<cerema_html_7f500ad39ffdff4e.png>

Centre d’études et d’expertise sur les risques, l’environnement, la 
mobilité et l’aménagement - *www.cerema.fr*
Direction territoriale Nord-Picardie – 44 terrue Jean Bart -CS 20275 - 
59019 Lille Cedex
Siège social : Cité des Mobilités - 25 avenue François Mitterrand - CS 
92 803 - 69674 Bron Cedex - tél : +33 (0)4 72 14 30 30

**Comment by anitagraser** [comment]
Yes, I downloaded the unpublished version and deleted my comment here when I noticed that it was fixed.

Do you have some documentation that explains the general workflow and order for using all the different tools in the toolbox?

**Comment by crocovert** [comment]
I have elements (but in french unforntunately) . I am working on it just now (in english) to explain the general workflow and and will send it asap

**Comment by anitagraser** [comment]
Great, thank you! Even the French documentation would be a great start. Many in our community can read or Google translate it.

**Comment by crocovert** [comment]
I've put 3 documents (pdf in root directory and odt in help directory)
EN_Network_provider.pdf: Provider global process (English)
FR_Multimodal_accessibility_tutorial.pdf: Tutorial based on scripts (Qgis2 versions) (French)
Musliw_documentation_english.pdf: Mulsiw doc (file format and parameters) (English)
I hope this helps
