### ISSUE TITLE
Please remove unnecessary files

### ISSUE THREAD

**Issue by pcav** [crocovert/networks#7]
.pyc etc.
They are generated automatically during installation.
Thanks.

**Comment by crocovert** [comment]
Ok it's done

**Comment by pcav** [comment]
I still see https://github.com/crocovert/networks/tree/master/__pycache__

**Comment by crocovert** [comment]
Ok.
Sorry, I had only removed pyc files from the plugins.qgis site
Now I've removed them on github too

**Comment by pcav** [comment]
I think also https://github.com/crocovert/networks/tree/master/.vs/Muslic/v15 should better be removed

**Comment by crocovert** [comment]
ok
