### ISSUE TITLE
Plugin loading problem

### ISSUE THREAD

**Issue by ulistream** [crocovert/networks#8]
Hi, 

I can't load the plugin : 
![screenshot 225](https://user-images.githubusercontent.com/31889687/49927451-374f8600-febe-11e8-80e4-286b04a0ea05.jpg)
Any idea if the problem comes from the plugin or my QGIS installation?

**Comment by crocovert** [comment]
Hello,

It seems that you don't have your userLocale correctly defined.
Try to open the python console

enter the following expression and inform me what it returns

QSettings().value('locale/userLocale')

For me it return 'fr' as my locale Qgis is in french

Thank you

**Comment by ulistream** [comment]
Thanks for answer. 
Mine is 'fr_CH' (french/switzerland).
But... don't ask me why, it works now! I did'nt do anything.
